### ISSUE TITLE
Support for MongoID

### ISSUE THREAD

**Issue by bglbruno** [volmer/bootsy#149]
In [bootsy-mongoid](https://github.com/volmer/bootsy-mongoid), has a warning saying the project was discontinued and would be merged in this repo, 2 years ago.

But a try using that and it's not working. I'm using ruby 2.2.2, rails 4.2.0

```ruby
gem 'carrierwave-mongoid', :require => 'carrierwave/mongoid'                     
gem 'bootsy'
```

```shell
rails generate bootsy:install

/home/bglbruno/.rvm/gems/ruby-2.2.2/gems/bootsy-2.1.0/lib/bootsy/activerecord/image_gallery.rb:12:in `<module:Bootsy>': uninitialized constant Bootsy::ActiveRecord (NameError)
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/bootsy-2.1.0/lib/bootsy/activerecord/image_gallery.rb:1:in `<top (required)>'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/bootsy-2.1.0/lib/bootsy/engine.rb:29:in `block (2 levels) in <class:Engine>'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/bootsy-2.1.0/lib/bootsy/engine.rb:28:in `each'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/bootsy-2.1.0/lib/bootsy/engine.rb:28:in `block in <class:Engine>'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/bglbruno/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/bglbruno/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/bglbruno/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/bglbruno/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/bglbruno/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/bglbruno/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/bglbruno/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/bglbruno/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/bglbruno/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
	from /home/bglbruno/workspace/blog/config/environment.rb:5:in `<top (required)>'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:92:in `preload'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /home/bglbruno/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/bglbruno/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/bglbruno/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by volmer** [comment]
Turns out the Mongoid support was never merged. Sorry about that.
