### ISSUE TITLE
NameError: uninitialized constant Bootsy::ApplicationHelper

### ISSUE THREAD

**Issue by stillwyw** [volmer/bootsy#196]
Got this when trying to do db migration. Did not happen on development or testing env.

Production env only diff is:
rubinus 2.1.2

```
RAILS_ENV=production bundle exec rake db:migrate
rake aborted!
NameError: uninitialized constant Bootsy::ApplicationHelper
/usr/local/rvm/rubies/rbx-2.5.2/gems/bundler/gems/bootsy-8a0d652e1189/lib/bootsy/engine.rb:15:in `__script__'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:438:in `make_lambda'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:184:in `simple'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:185:in `simple'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/actionpack-4.1.6/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/actionpack-4.1.6/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/railties-4.1.6/lib/rails/application/finisher.rb:52:in `__script__'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/railties-4.1.6/lib/rails/initializable.rb:55:in `run_initializers'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:150:in `tsort_each'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:183:in `each_strongly_connected_component'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:219:in `each_strongly_connected_component_from'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:0:in `each_strongly_connected_component'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:180:in `each_strongly_connected_component'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:148:in `tsort_each'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/railties-4.1.6/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/railties-4.1.6/lib/rails/application.rb:300:in `initialize!'
/data/web/bootique/config/environment.rb:5:in `__script__'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/railties-4.1.6/lib/rails/application.rb:276:in `require_environment!'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/railties-4.1.6/lib/rails/application.rb:389:in `run_tasks_blocks'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize'
/usr/local/rvm/rubies/rbx-2.5.2/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize'
```

**Comment by volmer** [comment]
Do you have the same problem with MRI? We don't officially support Rubinius.

**Comment by volmer** [comment]
Closing this for now. Feel free to reopen it if it also happens with MRI.
